# Disable codegen and new architecture
ENV['DISABLE_CODEGEN'] = '1'
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['USE_HERMES'] = '0'
ENV['NO_FLIPPER'] = '1'
ENV['CI'] = '1'

platform :macos, '11.0'

# Create dummy ReactCodegen podspec in BOTH locations (project root and macos folder)
# Some scripts look relative to project root, others relative to macos/
[File.join(__dir__, '..', 'build', 'generated', 'ios'),
 File.join(__dir__, 'build', 'generated', 'ios')].each do |codegen_path|
  FileUtils.mkdir_p(codegen_path)
  File.write(File.join(codegen_path, 'ReactCodegen.podspec'), <<~'PODSPEC')
Pod::Spec.new do |s|
  s.name         = "ReactCodegen"
  s.version      = "0.0.1"
  s.summary      = "Dummy spec for macOS build"
  s.homepage     = "https://reactnative.dev"
  s.license      = "MIT"
  s.author       = "Meta"
  s.platforms    = { :osx => "11.0" }
  s.source       = { :git => "", :tag => "0.0.1" }
  s.source_files = "dummy.h"
end
  PODSPEC
  File.write(File.join(codegen_path, 'dummy.h'), "// Dummy file\n")
end

# Stub out the codegen script before it gets called
ENV['REACT_NATIVE_PATH'] = File.join(__dir__, '..', 'node_modules', 'react-native-macos')

# Load react_native_pods.rb to get helper functions, but catch errors
begin
  require Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
      "react-native-macos/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )', __dir__]).strip
rescue => e
  Pod::UI.warn "Note: #{e.message}"
end

# Override codegen-related methods to be no-ops
def build_codegen!(*args); end
def build_hermes!(*args); end
def checkAndGenerateEmptyThirdPartyProvider!(*args); end

# Override prepare_react_native_project! if it wasn't loaded or to prevent codegen
def prepare_react_native_project!
  # Skip codegen preparation
end

target 'BlinkBuddy-macOS' do
  rn_path = '../node_modules/react-native-macos'

  use_react_native!(
    :path => rn_path,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    if defined?(react_native_post_install)
      react_native_post_install(
        installer,
        rn_path,
        :mac_catalyst_enabled => false
      )
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
